import './globals.css'
import Head from 'next/head'
export const metadata = {
  title:"OYO Clone", 
  description:"Generated by aman",
  icons:{
    icon: [
      '/favicon.ico?v-4'
    ],
    apple: [
     '/apple-touc-icon.png?v-4'
    ]
  },
  manifest: '/site.webmanifest'
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body>
        {children}
        </body>
    </html>
  )
}
